#!/usr/bin/bash
if [ -d ./protonScript ]; then
    rm -R ./protonScript
fi
mkdir protonScript
cd protonScript
curl -svLOJ $(curl -s https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest | grep browser_download_url | cut -d\" -f4 | egrep .tar.gz)
if [ ! -d ~/.steam/root/compatibilitytools.d/ ]; then
    mkdir ~/.steam/root/compatibilitytools.d/
fi
tar -xvf ./GE-Proton*.tar.gz -C ~/.steam/root/compatibilitytools.d/
cd ../
rm -R ./protonScript
