#!/usr/bin/bash
if [ -d ./protonScript ]; then
rm -R ./protonScript
fi
mkdir protonScript
cd protonScript
URL=$(curl -s https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest | jq -r .tarball_url | cat)
wget $URL
tar -xf ./GE-Proton*
if [ ! -d ~/.steam/root/compatibilitytools.d/ ]; then
mkdir ~/.steam/root/compatibilitytools.d/
fi
tar -xf ./GE-Proton*.tar.gz -C ~/.steam/root/compatibilitytools.d/
cd ../
rm -R ./protonScript
